Repository unosquare/uno-react, pull requests merged in 2019-02, with the labels that each got.

#2 Added confirmation dialog
  src/classes/ConfirmationDialog.jsx
  src/classes/index.js
Labels: enhancement

#3 adding useNow
  src/hooks/index.js
  src/hooks/useNow.js
Labels: good first issue

#9 add jss alpha version
  package.json
Labels: bug

#12 Issue6 document all the hooks
  README.md
Labels: documentation

#16 ConfirmationDialogTextColor
  src/classes/ConfirmationDialog.jsx
Labels: enhancement

#20 Issue17 typography confirmation dialog text color
  src/classes/ConfirmationDialog.jsx
Labels: enhancement

#24 Issue5 config unit test
  README.md
  lib/classes/ConfirmationDialog.js
  lib/classes/GlobalSnackbar.js
  lib/functions/humanize.js
  lib/functions/index.js
  lib/functions/withEnter.js
  lib/hoc/ClickOutside.js
  lib/hoc/index.js
  lib/index.js
  package-lock.json
  package.json
  src/classes/ConfirmationDialog.jsx
  src/classes/GlobalSnackbar.jsx
  src/functions/humanize.js
  src/functions/index.js
  src/functions/withEnter.js
  src/hoc/ClickOutside.jsx
  src/hoc/index.js
  src/index.js
  test/classes/ConfirmationDialog.spec.jsx
  test/classes/CustomSnackbarContent.spec.jsx
  test/classes/ErrorBoundary.spec.jsx
  test/classes/TextValidator.spec.jsx
  test/classes/TextValidatorImplementation.jsx
  test/classes/TextValidatorImplementation.spec.jsx
  test/classes/Title.spec.jsx
  test/dataSource/__mocks__/DataSourceContext.js
  test/dataSource/__mocks__/TestContextHelper.js
  test/functions/ButtonWithLoading.spec.jsx
  test/functions/ColorGenerator.spec.jsx
  test/functions/LoadingIcon.spec.jsx
  test/functions/Validations.spec.jsx
  test/hooks/UseStateForModelImplementation.jsx
  test/hooks/useStateForModel.spec.jsx
  test/setupTest.js
Labels: enhancement
